CREATE DATABASE IF NOT EXISTS constructora;
USE constructora;

CREATE TABLE contactos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  mensaje TEXT NOT NULL,
  creado TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chats (
  id INT AUTO_INCREMENT PRIMARY KEY,
  usuario TEXT NOT NULL,
  asistente TEXT NOT NULL,
  creado TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SELECT * FROM chats ORDER BY creado DESC;